FROM osixia/openldap:1.4.0
MAINTAINER Your Name <stephane.trochu23@gmail.com>

ADD bootstrap /container/service/slapd/assets/config/bootstrap
ADD certs /container/service/slapd/assets/certs
ADD environment /container/environment/01-custom
